spaces:
  -
    name: GitHub Sync
    order:
      - github_sync_job_count
      - github_sync_job_95th_percentile
      - github_sync_job_median
      - sidekiq_queue_sizes
      - github_sync_load_avg
      - github_sync_memory_usage
      - postgres_load_avg_maroon
      - api_overall_request_95th
      - hub_worker_handle_95th

accounts:
  com:
    user: mathias@travis-ci.com
    vars:
      app: travis-pro-github-sync
      db_source: travis-pro-production.heroku_postgresql_maroon
      db_name: maroon

  org:
    user: mathias@travis-ci.org
    vars:
      app: travis-github-sync
      db_source: travis-production.heroku_postgresql_white
      db_name: white
